# NumPy for AI Students: A Step-by-Step Tutorial

**Goal:** Learn NumPy from scratch and apply it to real AI/ML tasks such as normalization, softmax, linear regression, and a neural-network forward pass.

## Table of Contents
1. Why NumPy?
2. Installation and Import
3. Creating Arrays
4. Array Attributes and Data Types
5. Indexing and Slicing
6. Boolean Masking and Fancy Indexing
7. Reshaping, Stacking, and Splitting
8. Vectorized Operations and Universal Functions
9. Broadcasting
10. Aggregations and the `axis` Parameter
11. Linear Algebra
12. Random Numbers
13. Useful Functions for Data Processing
14. Performance: Loops vs. Vectorization
15. Saving and Loading Arrays
16. AI Mini-Projects
17. Exercises
18. Cheat Sheet

## 1. Why NumPy?

**NumPy** (Numerical Python) is the foundation of the scientific Python ecosystem. Libraries such as **Pandas, scikit-learn, SciPy, Matplotlib, TensorFlow, and PyTorch** are built on, or interoperate with, NumPy arrays.

| Python list | NumPy array |
|---|---|
| Can hold mixed types | Holds a single data type (homogeneous) |
| Slow for numerical loops | Fast (C-implemented, vectorized) |
| No built-in math on whole collection | Element-wise math on whole arrays |
| Higher memory usage | Compact memory layout |

In AI, almost everything is a tensor (an n-dimensional array):
- A **dataset** is a 2D array: `(samples, features)`
- A **grayscale image** is a 2D array: `(height, width)`
- A **color image** is a 3D array: `(height, width, channels)`
- A **batch of images** is a 4D array: `(batch, height, width, channels)`

## 2. Installation and Import

Install NumPy (only needed once; most environments like Google Colab already have it):

```bash
pip install numpy
```

By convention, NumPy is imported with the alias `np`.

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.2.0


## 3. Creating Arrays

### 3.1 From Python lists

In [ ]:
a = np.array([1, 2, 3, 4, 5])          # 1D array (vector)
b = np.array([[1, 2, 3],
              [4, 5, 6]])              # 2D array (matrix)
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])       # 3D array (tensor)

print("1D:\n", a)
print("2D:\n", b)
print("3D:\n", c)

### 3.2 Built-in array constructors

In [2]:
print("zeros:\n", np.zeros((2, 3)))
print("ones:\n", np.ones((3, 2)))
print("full:\n", np.full((2, 2), 7))
print("identity:\n", np.eye(3))
print("empty (uninitialized, values are arbitrary):\n", np.empty((2, 2)))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
full:
 [[7 7]
 [7 7]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
empty (uninitialized, values are arbitrary):
 [[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]


### 3.3 Ranges and evenly spaced numbers

In [ ]:
print("arange(0, 10, 2):", np.arange(0, 10, 2))        # start, stop (exclusive), step
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))      # start, stop (inclusive), number of points
print("logspace(0, 3, 4):", np.logspace(0, 3, 4))      # 10^0 ... 10^3

### 3.4 Creating arrays "like" another array

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.zeros_like(x))
print(np.ones_like(x))
print(np.full_like(x, 9))

> **Tip:** `np.arange` uses a step size while `np.linspace` uses the number of points. Prefer `linspace` for floating-point ranges to avoid rounding surprises.

## 4. Array Attributes and Data Types

Every array has important attributes:

| Attribute | Meaning |
|---|---|
| `ndim` | Number of dimensions (axes) |
| `shape` | Size of each dimension |
| `size` | Total number of elements |
| `dtype` | Data type of elements |
| `itemsize` | Bytes per element |
| `nbytes` | Total bytes used |

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("ndim    :", arr.ndim)
print("shape   :", arr.shape)
print("size    :", arr.size)
print("dtype   :", arr.dtype)
print("itemsize:", arr.itemsize, "bytes")
print("nbytes  :", arr.nbytes, "bytes")

### Data types (`dtype`)

Common types: `int8, int16, int32, int64, uint8, float16, float32, float64, bool`.

In deep learning, **`float32`** is the standard type (it uses half the memory of `float64`). Images are often stored as **`uint8`** (0 to 255).

In [ ]:
f64 = np.array([1.5, 2.5, 3.5])                 # default float is float64
f32 = np.array([1.5, 2.5, 3.5], dtype=np.float32)
img = np.array([0, 128, 255], dtype=np.uint8)

print(f64.dtype, f32.dtype, img.dtype)

# Converting types with astype (returns a new array)
converted = f64.astype(np.int32)
print("float -> int (truncates):", converted)

# Beware of overflow in unsigned integers!
print("uint8 overflow: 250 + 10 =", np.uint8(250) + np.uint8(10))

## 5. Indexing and Slicing

Indexing starts at **0**. Negative indices count from the end.

In [ ]:
v = np.array([10, 20, 30, 40, 50, 60])

print("First   :", v[0])
print("Last    :", v[-1])
print("Slice   :", v[1:4])     # indices 1,2,3
print("Step    :", v[::2])     # every second element
print("Reversed:", v[::-1])

### 2D indexing: `array[row, column]`

In [ ]:
M = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

print("M[0, 0]   =", M[0, 0])
print("M[1, 2]   =", M[1, 2])
print("Row 1     =", M[1])          # same as M[1, :]
print("Column 2  =", M[:, 2])
print("Sub-matrix (rows 0-1, cols 1-2):\n", M[:2, 1:3])

### Views vs. copies (very important!)

Basic slicing returns a **view**, not a copy. Modifying a view modifies the original array. Use `.copy()` if you need independence.

In [ ]:
original = np.array([1, 2, 3, 4, 5])

view = original[1:4]
view[0] = 999
print("After modifying the view  :", original)

original = np.array([1, 2, 3, 4, 5])
safe = original[1:4].copy()
safe[0] = 999
print("After modifying the copy  :", original)

## 6. Boolean Masking and Fancy Indexing

### 6.1 Boolean masks
A comparison produces a boolean array which can be used to filter data. This is extremely common in data cleaning.

In [ ]:
scores = np.array([55, 72, 90, 38, 85, 61, 99])

mask = scores > 60
print("Mask    :", mask)
print("Filtered:", scores[mask])
print("Direct  :", scores[scores > 60])

# Combining conditions: use & (and), | (or), ~ (not) with parentheses
print("Between 60 and 90:", scores[(scores >= 60) & (scores <= 90)])
print("Not passing      :", scores[~(scores >= 50)])

# Modify values using a mask
scores_copy = scores.copy()
scores_copy[scores_copy < 50] = 50
print("Floor at 50:", scores_copy)

### 6.2 Fancy indexing (index with arrays of integers)

In [ ]:
data = np.array([100, 200, 300, 400, 500])
idx = [0, 2, 4]
print(data[idx])

M = np.arange(12).reshape(3, 4)
print("Rows 0 and 2:\n", M[[0, 2]])
print("Pairs (0,1) and (2,3):", M[[0, 2], [1, 3]])

## 7. Reshaping, Stacking, and Splitting

### 7.1 Reshape
`reshape` changes the shape without changing the data. The total number of elements must stay the same. Use `-1` to let NumPy infer one dimension.

In [ ]:
x = np.arange(12)
print("Original:", x)
print("(3, 4):\n", x.reshape(3, 4))
print("(2, 6):\n", x.reshape(2, 6))
print("(2, -1) -> inferred (2, 6):\n", x.reshape(2, -1))
print("(2, 3, 2):\n", x.reshape(2, 3, 2))

### 7.2 Flatten, ravel, and transpose

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("flatten (copy):", M.flatten())
print("ravel (view if possible):", M.ravel())
print("Transpose M.T:\n", M.T)
print("Shape before/after transpose:", M.shape, "->", M.T.shape)

### 7.3 Adding and removing dimensions

In [ ]:
v = np.array([1, 2, 3])
print("Original shape:", v.shape)

col = v[:, np.newaxis]          # same as np.expand_dims(v, axis=1)
print("Column vector shape:", col.shape)

row = np.expand_dims(v, axis=0)
print("Row vector shape   :", row.shape)

print("Squeeze back:", np.squeeze(col).shape)

### 7.4 Concatenate and stack

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("concatenate axis=0 (vertical):\n", np.concatenate([a, b], axis=0))
print("concatenate axis=1 (horizontal):\n", np.concatenate([a, b], axis=1))
print("vstack:\n", np.vstack([a, b]))
print("hstack:\n", np.hstack([a, b]))
print("stack (new axis) shape:", np.stack([a, b]).shape)   # (2, 2, 2)

### 7.5 Splitting

In [ ]:
x = np.arange(12).reshape(4, 3)
top, bottom = np.split(x, 2, axis=0)
print("Top:\n", top)
print("Bottom:\n", bottom)

## 8. Vectorized Operations and Universal Functions

NumPy applies operations **element-wise** to entire arrays without Python loops. This is called **vectorization**.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b :", a + b)
print("b - a :", b - a)
print("a * b :", a * b)       # element-wise, NOT matrix multiplication
print("b / a :", b / a)
print("a ** 2:", a ** 2)
print("b // 3:", b // 3)
print("b % 3 :", b % 3)

### Universal functions (ufuncs)

In [ ]:
x = np.array([0, np.pi / 2, np.pi])

print("sin :", np.sin(x))
print("cos :", np.cos(x))
print("exp :", np.exp([0, 1, 2]))
print("log :", np.log([1, np.e, np.e**2]))
print("sqrt:", np.sqrt([1, 4, 9, 16]))
print("abs :", np.abs([-3, 2, -1]))
print("round:", np.round([1.234, 5.678], 1))
print("floor/ceil:", np.floor(2.7), np.ceil(2.2))

### Activation functions with ufuncs
Because ufuncs work on whole arrays, activation functions are one-liners.

In [ ]:
z = np.linspace(-5, 5, 11)

sigmoid = 1 / (1 + np.exp(-z))
relu = np.maximum(0, z)
tanh = np.tanh(z)

print("z      :", z)
print("sigmoid:", np.round(sigmoid, 3))
print("relu   :", relu)
print("tanh   :", np.round(tanh, 3))

## 9. Broadcasting

**Broadcasting** lets NumPy perform operations on arrays of different shapes.

**Rules** (compare shapes from the right-most dimension):
1. Dimensions are compatible if they are **equal** or one of them is **1**.
2. Missing dimensions are treated as 1.
3. A dimension of size 1 is "stretched" to match the other.

In [ ]:
# Scalar with array
a = np.array([1, 2, 3])
print(a + 10)

# (2, 3) + (3,) -> (2, 3)
M = np.array([[1, 2, 3],
              [4, 5, 6]])
row = np.array([10, 20, 30])
print("Add row to every row:\n", M + row)

# (2, 3) + (2, 1) -> (2, 3)
col = np.array([[100], [200]])
print("Add column to every column:\n", M + col)

# (3, 1) + (1, 3) -> (3, 3)  (outer-sum)
x = np.array([[1], [2], [3]])
y = np.array([[10, 20, 30]])
print("Outer sum:\n", x + y)

Incompatible shapes raise an error:

In [ ]:
try:
    np.ones((2, 3)) + np.ones((2,))     # (2,3) vs (2,) -> trailing dims 3 vs 2
except ValueError as e:
    print("ValueError:", e)

### AI use case: feature standardization via broadcasting
Subtract each column's mean and divide by its std for a `(samples, features)` matrix.

In [ ]:
X = np.array([[170, 65],
              [180, 80],
              [160, 55],
              [175, 72]], dtype=float)    # columns: height (cm), weight (kg)

mean = X.mean(axis=0)     # shape (2,)
std = X.std(axis=0)       # shape (2,)
X_std = (X - mean) / std  # (4,2) - (2,) -> broadcasting

print("Mean:", mean)
print("Std :", std)
print("Standardized:\n", np.round(X_std, 3))
print("New mean ~ 0:", np.round(X_std.mean(axis=0), 6))
print("New std  = 1:", X_std.std(axis=0))

## 10. Aggregations and the `axis` Parameter

Common aggregations: `sum, mean, median, std, var, min, max, prod`.

**Understanding `axis`:**
- `axis=0` -> operate **down the rows** (result has one value per column)
- `axis=1` -> operate **across the columns** (result has one value per row)

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Total sum      :", M.sum())
print("Sum axis=0     :", M.sum(axis=0))     # per column
print("Sum axis=1     :", M.sum(axis=1))     # per row
print("Mean           :", M.mean())
print("Max per column :", M.max(axis=0))
print("Min per row    :", M.min(axis=1))
print("Std            :", M.std())
print("Median         :", np.median(M))

### `keepdims=True` keeps the dimension, which is handy for broadcasting

In [ ]:
row_sums = M.sum(axis=1, keepdims=True)
print("Shape:", row_sums.shape)
print("Row-normalized (each row sums to 1):\n", M / row_sums)

### Cumulative operations and argument-based functions

In [ ]:
v = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print("cumsum :", np.cumsum(v))
print("cumprod:", np.cumprod([1, 2, 3, 4]))
print("argmax :", v.argmax(), "-> value", v.max())
print("argmin :", v.argmin(), "-> value", v.min())

# Boolean aggregations
print("any > 8:", (v > 8).any())
print("all > 0:", (v > 0).all())
print("count > 3:", (v > 3).sum())      # True counts as 1

## 11. Linear Algebra

Linear algebra is the mathematical backbone of machine learning.

### 11.1 Dot product and matrix multiplication

In [ ]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print("Dot product:", np.dot(u, v), "|", u @ v)

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Element-wise A * B:\n", A * B)
print("Matrix product A @ B:\n", A @ B)
print("np.matmul(A, B) equal?:", np.array_equal(A @ B, np.matmul(A, B)))

> **Shape rule:** `(m, n) @ (n, p) -> (m, p)`. The inner dimensions must match.

### 11.2 Transpose, trace, determinant, inverse

In [ ]:
A = np.array([[4., 7.],
              [2., 6.]])

print("Transpose:\n", A.T)
print("Trace    :", np.trace(A))
print("Det      :", np.linalg.det(A))

A_inv = np.linalg.inv(A)
print("Inverse:\n", A_inv)
print("A @ A_inv ~ Identity:\n", np.round(A @ A_inv, 10))

### 11.3 Solving linear systems: `Ax = b`

In [ ]:
A = np.array([[3., 1.],
              [1., 2.]])
b = np.array([9., 8.])

x = np.linalg.solve(A, b)
print("Solution x:", x)
print("Check A @ x:", A @ x)

### 11.4 Norms, eigenvalues, and SVD

In [ ]:
v = np.array([3., 4.])
print("L2 norm :", np.linalg.norm(v))
print("L1 norm :", np.linalg.norm(v, ord=1))

A = np.array([[2., 0.],
              [0., 3.]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues :", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

M = np.array([[1., 2.], [3., 4.], [5., 6.]])
U, S, Vt = np.linalg.svd(M, full_matrices=False)
print("Singular values:", S)
print("Shapes U, S, Vt:", U.shape, S.shape, Vt.shape)

## 12. Random Numbers

Random numbers are used for weight initialization, data shuffling, sampling, and augmentation.

The modern recommended API is `np.random.default_rng(seed)`. A **seed** makes results reproducible.

In [ ]:
rng = np.random.default_rng(seed=42)

print("Uniform [0,1)        :", rng.random(3))
print("Random ints [0,10)   :", rng.integers(0, 10, size=5))
print("Standard normal      :", rng.standard_normal(3))
print("Normal(mean=5, std=2):", rng.normal(5, 2, size=3))
print("Random matrix (2x3):\n", rng.random((2, 3)))

### Shuffling, choosing, and permutations

In [ ]:
rng = np.random.default_rng(0)

items = np.arange(10)
print("Permutation :", rng.permutation(items))
print("Choice (no replacement):", rng.choice(items, size=4, replace=False))
print("Choice (with replacement):", rng.choice(items, size=4, replace=True))

# Weighted choice
print("Weighted:", rng.choice(["A", "B", "C"], size=10, p=[0.7, 0.2, 0.1]))

### AI use case: weight initialization
Xavier/Glorot-style initialization for a layer with 4 inputs and 3 outputs.

In [ ]:
rng = np.random.default_rng(1)
n_in, n_out = 4, 3

W = rng.standard_normal((n_in, n_out)) * np.sqrt(2.0 / (n_in + n_out))
b = np.zeros(n_out)

print("W:\n", np.round(W, 3))
print("b:", b)

## 13. Useful Functions for Data Processing

### 13.1 `np.where` (vectorized if-else)

In [ ]:
x = np.array([-2, -1, 0, 1, 2])

print("np.where(x > 0, 'pos', 'non-pos'):", np.where(x > 0, "pos", "non-pos"))
print("Leaky ReLU:", np.where(x > 0, x, 0.1 * x))
print("Indices where x > 0:", np.where(x > 0)[0])

### 13.2 Sorting

In [ ]:
v = np.array([30, 10, 50, 20, 40])

print("sort    :", np.sort(v))
print("argsort :", np.argsort(v))              # indices that would sort the array
print("top-3 indices:", np.argsort(v)[::-1][:3])
print("descending:", np.sort(v)[::-1])

M = np.array([[3, 1], [2, 5], [1, 9]])
print("Sort rows by 1st column:\n", M[np.argsort(M[:, 0])])

### 13.3 Unique values and counting

In [ ]:
labels = np.array([0, 1, 1, 2, 0, 2, 2, 2])
values, counts = np.unique(labels, return_counts=True)
print("Classes:", values)
print("Counts :", counts)
print("bincount:", np.bincount(labels))

### 13.4 Clipping, set operations, and membership

In [ ]:
x = np.array([-5, 0, 5, 10, 15])
print("clip(0, 10):", np.clip(x, 0, 10))

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("intersect1d:", np.intersect1d(a, b))
print("union1d    :", np.union1d(a, b))
print("setdiff1d  :", np.setdiff1d(a, b))
print("isin       :", np.isin(a, [2, 4]))

### 13.5 Handling missing values (`NaN`)

In [ ]:
data = np.array([1.0, np.nan, 3.0, np.nan, 5.0])

print("isnan       :", np.isnan(data))
print("sum (broken):", data.sum())
print("nansum      :", np.nansum(data))
print("nanmean     :", np.nanmean(data))

# Replace NaN with the mean of valid values
filled = np.where(np.isnan(data), np.nanmean(data), data)
print("Filled:", filled)

### 13.6 Meshgrid (useful for plotting functions and decision boundaries)

In [ ]:
x = np.linspace(-1, 1, 3)
y = np.linspace(-1, 1, 3)
XX, YY = np.meshgrid(x, y)
print("XX:\n", XX)
print("YY:\n", YY)
print("XX^2 + YY^2:\n", XX**2 + YY**2)

## 14. Performance: Loops vs. Vectorization

Let us measure how much faster NumPy is than pure Python.

In [ ]:
import time

n = 1_000_000
py_list = list(range(n))
np_array = np.arange(n)

# Pure Python loop
start = time.perf_counter()
result_py = [x * 2 for x in py_list]
t_py = time.perf_counter() - start

# NumPy vectorized
start = time.perf_counter()
result_np = np_array * 2
t_np = time.perf_counter() - start

print(f"Python list : {t_py * 1000:.2f} ms")
print(f"NumPy array : {t_np * 1000:.2f} ms")
print(f"Speed-up    : ~{t_py / t_np:.0f}x")

> **Rule of thumb:** If you write a `for` loop over array elements, there is usually a vectorized NumPy alternative that is much faster.

## 15. Saving and Loading Arrays

In [ ]:
import os, tempfile

arr = np.arange(10)
mat = np.random.default_rng(0).random((3, 3))

tmp = tempfile.mkdtemp()

# Single array: .npy
np.save(os.path.join(tmp, "arr.npy"), arr)
loaded = np.load(os.path.join(tmp, "arr.npy"))
print("Loaded .npy:", loaded)

# Multiple arrays: .npz (compressed with savez_compressed)
np.savez(os.path.join(tmp, "bundle.npz"), vector=arr, matrix=mat)
bundle = np.load(os.path.join(tmp, "bundle.npz"))
print("Keys in .npz:", list(bundle.keys()))
print("matrix:\n", np.round(bundle["matrix"], 3))

# Text / CSV
np.savetxt(os.path.join(tmp, "mat.csv"), mat, delimiter=",", fmt="%.4f")
print("Loaded CSV:\n", np.loadtxt(os.path.join(tmp, "mat.csv"), delimiter=","))

## 16. AI Mini-Projects

Now we apply everything we have learned to real machine-learning tasks using only NumPy.

### Project 1: Min-Max Normalization and Z-score Standardization

In [ ]:
rng = np.random.default_rng(7)
X = rng.integers(10, 100, size=(5, 3)).astype(float)
print("Raw data:\n", X)

# Min-Max scaling to [0, 1]
X_minmax = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
print("\nMin-Max scaled:\n", np.round(X_minmax, 3))

# Z-score standardization
X_z = (X - X.mean(axis=0)) / X.std(axis=0)
print("\nZ-score standardized:\n", np.round(X_z, 3))

### Project 2: Softmax and Cross-Entropy Loss

**Softmax** converts raw scores (logits) into probabilities:

$$\text{softmax}(z_i) = \frac{e^{z_i}}{\sum_j e^{z_j}}$$

We subtract the max for numerical stability.

In [ ]:
def softmax(logits):
    shifted = logits - np.max(logits, axis=-1, keepdims=True)   # numerical stability
    exp = np.exp(shifted)
    return exp / np.sum(exp, axis=-1, keepdims=True)

logits = np.array([[2.0, 1.0, 0.1],
                   [0.5, 2.5, 0.3]])
probs = softmax(logits)

print("Probabilities:\n", np.round(probs, 3))
print("Rows sum to 1:", probs.sum(axis=1))

# Cross-entropy loss
y_true = np.array([0, 1])                     # correct class indices
loss = -np.mean(np.log(probs[np.arange(len(y_true)), y_true]))
print("Cross-entropy loss:", round(loss, 4))

### Project 3: One-Hot Encoding

In [ ]:
labels = np.array([0, 2, 1, 2, 0])
num_classes = 3

one_hot = np.eye(num_classes)[labels]
print(one_hot)

### Project 4: Similarity Measures (Euclidean distance and Cosine similarity)
These are used in k-NN, recommendation systems, and word/sentence embeddings.

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 4.0, 6.5])

euclidean = np.linalg.norm(a - b)
cosine = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("Euclidean distance:", round(euclidean, 4))
print("Cosine similarity :", round(cosine, 4))

# k-NN style: find the closest points to a query without loops
points = np.array([[0, 0], [1, 1], [5, 5], [2, 1], [9, 9]], dtype=float)
query = np.array([1.5, 1.0])
dists = np.linalg.norm(points - query, axis=1)      # broadcasting
nearest = np.argsort(dists)[:2]
print("\nDistances:", np.round(dists, 3))
print("2 nearest point indices:", nearest)

### Project 5: Train/Test Split from scratch

In [ ]:
def train_test_split(X, y, test_size=0.2, seed=0):
    rng = np.random.default_rng(seed)
    indices = rng.permutation(len(X))
    split = int(len(X) * (1 - test_size))
    train_idx, test_idx = indices[:split], indices[split:]
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]

X = np.arange(20).reshape(10, 2)
y = np.arange(10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print("Train:", X_train.shape, "Test:", X_test.shape)
print("Test labels:", y_test)

### Project 6: Linear Regression

We will generate data from $y = 3x + 4 + \text{noise}$ and recover the parameters in two ways.

**(a) Normal equation:** $\theta = (X^T X)^{-1} X^T y$

In [ ]:
rng = np.random.default_rng(42)
n = 100
x = rng.uniform(0, 10, size=n)
y = 3 * x + 4 + rng.normal(0, 1.0, size=n)

# Add bias column of ones -> design matrix shape (n, 2)
X = np.column_stack([np.ones(n), x])

theta = np.linalg.solve(X.T @ X, X.T @ y)       # more stable than explicit inverse
print(f"Normal equation -> intercept: {theta[0]:.3f}, slope: {theta[1]:.3f}")

**(b) Gradient descent:** iteratively update parameters to minimize Mean Squared Error.

In [ ]:
theta_gd = np.zeros(2)
lr = 0.01
epochs = 2000

for epoch in range(epochs):
    predictions = X @ theta_gd
    error = predictions - y
    gradient = (2 / n) * (X.T @ error)
    theta_gd -= lr * gradient
    if epoch % 400 == 0:
        mse = np.mean(error ** 2)
        print(f"Epoch {epoch:4d} | MSE = {mse:.4f}")

print(f"\nGradient descent -> intercept: {theta_gd[0]:.3f}, slope: {theta_gd[1]:.3f}")

### Project 7: Forward Pass of a Small Neural Network

Architecture: `Input(4) -> Dense(5) + ReLU -> Dense(3) + Softmax`

In [ ]:
rng = np.random.default_rng(3)

batch_size = 6
X = rng.standard_normal((batch_size, 4))           # (6, 4)

W1 = rng.standard_normal((4, 5)) * 0.5             # (4, 5)
b1 = np.zeros(5)
W2 = rng.standard_normal((5, 3)) * 0.5             # (5, 3)
b2 = np.zeros(3)

# Layer 1
z1 = X @ W1 + b1                                    # (6, 5)   bias is broadcast
a1 = np.maximum(0, z1)                              # ReLU

# Layer 2
z2 = a1 @ W2 + b2                                   # (6, 3)
probs = softmax(z2)

print("Output shape:", probs.shape)
print("Probabilities:\n", np.round(probs, 3))
print("Predicted classes:", probs.argmax(axis=1))

### Project 8: Working with Images as Arrays
An image is just an array of numbers. Here we create a tiny synthetic image and manipulate it.

In [ ]:
# Create a synthetic 6x6 grayscale image with a bright square
img = np.zeros((6, 6), dtype=np.uint8)
img[2:4, 2:4] = 255
print("Original:\n", img)

# Normalize to [0, 1] float (typical preprocessing)
img_norm = img.astype(np.float32) / 255.0

# Invert
img_inv = 255 - img

# Flip horizontally / vertically
flipped_lr = np.fliplr(img)
flipped_ud = np.flipud(img)

# Rotate 90 degrees
rotated = np.rot90(img)

# Random color image: (height, width, channels)
rng = np.random.default_rng(0)
rgb = rng.integers(0, 256, size=(4, 4, 3), dtype=np.uint8)
gray = rgb.mean(axis=2).astype(np.uint8)       # average the channels
print("\nRGB shape :", rgb.shape)
print("Gray shape:", gray.shape)
print("Batch of 8 images shape:", np.stack([rgb] * 8).shape)

## 17. Exercises

Try to solve each exercise yourself before looking at the solutions at the end of the notebook.

1. Create a 1D array of the even numbers from 2 to 20.
2. Create a `5x5` matrix where the border values are 1 and the inside values are 0.
3. Given `x = np.arange(1, 17).reshape(4, 4)`, extract the **diagonal**, the **last column**, and the **2x2 center block**.
4. Given `scores = np.array([45, 67, 89, 23, 90, 56, 78, 34, 99, 61])`, count how many scores are above the mean and replace all scores below 50 with 50.
5. Create a random `(100, 3)` matrix from a normal distribution with seed 0, then standardize each column and verify that the mean is about 0 and the standard deviation is 1.
6. Implement **sigmoid** and its derivative, then evaluate on `np.linspace(-6, 6, 7)`.
7. Given two matrices `A` of shape `(3, 4)` and `B` of shape `(4, 2)`, compute the product and state the resulting shape. Then explain why `B @ A` fails.
8. Compute the **pairwise Euclidean distance matrix** of 5 random 2D points using broadcasting (no loops). *Hint: `points[:, None, :] - points[None, :, :]`*.
9. Implement **accuracy** given `y_true` and `y_pred` arrays.
10. Implement a **confusion matrix** for a 3-class problem using NumPy only.

In [ ]:
# Write your solutions here

## Solutions

In [ ]:
# 1
print("1:", np.arange(2, 21, 2))

# 2
m = np.ones((5, 5))
m[1:-1, 1:-1] = 0
print("2:\n", m)

# 3
x = np.arange(1, 17).reshape(4, 4)
print("3 diagonal   :", np.diag(x))
print("3 last column:", x[:, -1])
print("3 center 2x2 :\n", x[1:3, 1:3])

# 4
scores = np.array([45, 67, 89, 23, 90, 56, 78, 34, 99, 61])
print("4 above mean:", (scores > scores.mean()).sum())
print("4 floored   :", np.where(scores < 50, 50, scores))

# 5
rng = np.random.default_rng(0)
data = rng.normal(loc=5, scale=3, size=(100, 3))
data_std = (data - data.mean(axis=0)) / data.std(axis=0)
print("5 mean:", np.round(data_std.mean(axis=0), 6), "std:", np.round(data_std.std(axis=0), 6))

# 6
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1 - s)

z = np.linspace(-6, 6, 7)
print("6 sigmoid   :", np.round(sigmoid(z), 4))
print("6 derivative:", np.round(sigmoid_derivative(z), 4))

# 7
A = np.ones((3, 4)); B = np.ones((4, 2))
print("7 A@B shape:", (A @ B).shape)
try:
    B @ A
except ValueError as e:
    print("7 B@A fails because (4,2)@(3,4) has mismatched inner dims 2 != 3")

# 8
points = np.random.default_rng(1).random((5, 2))
diff = points[:, None, :] - points[None, :, :]        # (5, 5, 2)
dist_matrix = np.sqrt((diff ** 2).sum(axis=-1))       # (5, 5)
print("8 distance matrix:\n", np.round(dist_matrix, 3))

# 9
def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

print("9 accuracy:", accuracy(np.array([0, 1, 2, 1]), np.array([0, 2, 2, 1])))

# 10
def confusion_matrix(y_true, y_pred, num_classes):
    cm = np.zeros((num_classes, num_classes), dtype=int)
    np.add.at(cm, (y_true, y_pred), 1)
    return cm

y_true = np.array([0, 1, 2, 2, 1, 0, 2])
y_pred = np.array([0, 2, 2, 2, 1, 1, 0])
print("10 confusion matrix (rows=true, cols=pred):\n", confusion_matrix(y_true, y_pred, 3))

## 18. Cheat Sheet

| Task | Code |
|---|---|
| Create from list | `np.array([1, 2, 3])` |
| Zeros / ones / identity | `np.zeros(s)`, `np.ones(s)`, `np.eye(n)` |
| Range / linspace | `np.arange(a, b, step)`, `np.linspace(a, b, n)` |
| Shape / dtype | `a.shape`, `a.dtype`, `a.astype(np.float32)` |
| Reshape / flatten | `a.reshape(r, c)`, `a.ravel()` |
| Transpose | `a.T` |
| Index / slice | `a[i, j]`, `a[:, 1]`, `a[::2]` |
| Boolean filter | `a[a > 0]` |
| Concatenate / stack | `np.concatenate`, `np.vstack`, `np.hstack`, `np.stack` |
| Aggregation | `a.sum(axis=0)`, `a.mean(axis=1)`, `a.std()` |
| Arg-functions | `a.argmax()`, `a.argmin()`, `np.argsort(a)` |
| Conditional | `np.where(cond, x, y)` |
| Matrix multiply | `A @ B`, `np.dot(A, B)` |
| Inverse / solve | `np.linalg.inv(A)`, `np.linalg.solve(A, b)` |
| Norm | `np.linalg.norm(v)` |
| Random | `rng = np.random.default_rng(0)`; `rng.random()`, `rng.normal()`, `rng.integers()` |
| Save / load | `np.save`, `np.load`, `np.savez` |

### Best practices
- **Vectorize** instead of looping.
- Remember that slices are **views**; use `.copy()` when needed.
- Check **shapes** often (`print(x.shape)`) because most bugs in ML code are shape bugs.
- Use **`float32`** for deep learning workloads.
- Use a **seeded generator** for reproducible experiments.
- Use `np.linalg.solve` instead of `np.linalg.inv` when solving systems.

### Next steps
- **Pandas** for tabular data
- **Matplotlib** for visualization
- **scikit-learn** for classic machine learning
- **PyTorch / TensorFlow** for deep learning (their tensors behave very similarly to NumPy arrays)

*Happy learning!*